import { Item } from "./types";

const rooms: Item[] = [
  {
    id: 1,
    name: "Salle 1",
    type: "Classe",
    locationX: 2,
    locationY: 4,
    superficie: 100,
  },
  {
    id: 2,
    name: "Toillet 1",
    type: "Rest room",
    locationX: 7,
    locationY: 4,
    superficie: 100,
  },
  {
    id: 3,
    name: "Salle 2",
    type: "Classe",
    locationX: 12,
    locationY: 4,
    superficie: 100,
  },
  {
    id: 4,
    name: "Salle 3",
    type: "Classe",
    locationX: 22,
    locationY: 4,
    superficie: 100,
  },
  {
    id: 5,
    name: "Salle 4",
    type: "Classe",
    locationX: 28,
    locationY: 4,
    superficie: 100,
  },
  {
    id: 6,
    name: "Salle 5",
    type: "Classe",
    locationX: 2,
    locationY: 7,
    superficie: 100,
  },
  {
    id: 7,
    name: "Salle 6",
    type: "Classe",
    locationX: 10,
    locationY: 9,
    superficie: 100,
  },
  {
    id: 8,
    name: "Salle Conférence",
    type: "Classe",
    locationX: 17,
    locationY: 9,
    superficie: 100,
  },
  {
    id: 9,
    name: "Salle 7",
    type: "Classe",
    locationX: 28,
    locationY: 7,
    superficie: 100,
  },
  {
    id: 10,
    name: "Salle 8",
    type: "Classe",
    locationX: 2,
    locationY: 14,
    superficie: 100,
  },
  {
    id: 11,
    name: "Direction",
    type: "Direction",
    locationX: 10,
    locationY: 14,
    superficie: 150,
  },
  {
    id: 12,
    name: "Salle 9",
    type: "Classe",
    locationX: 18,
    locationY: 14,
    superficie: 100,
  },
  {
    id: 13,
    name: "Toillet 2",
    type: "Class",
    locationX: 23,
    locationY: 14,
    superficie: 150,
  },
  {
    id: 14,
    name: "Salle 10",
    type: "Classe",
    locationX: 28,
    locationY: 14,
    superficie: 100,
  },
];

export default rooms;
