import { Item } from "./types";

const rooms: Item[] = [
  {
    id: 1,
    name: "Salle 1",
    type: "Classe",
    locationX: 28,
    locationY: 4,
    superficie: 100,
  },
  {
    id: 2,
    name: "Toillet 1",
    type: "Rest room",
    locationX: 28,
    locationY: 4,
    superficie: 100,
  },
  {
    id: 3,
    name: "Salle 2",
    type: "Classe",
    locationX: 28,
    locationY: 4,
    superficie: 100,
  },
  {
    id: 4,
    name: "Salle 3",
    type: "Classe",
    locationX: 28,
    locationY: 4,
    superficie: 100,
  },
  {
    id: 5,
    name: "Salle 4",
    type: "Classe",
    locationX: 28,
    locationY: 4,
    superficie: 100,
  },
  {
    id: 6,
    name: "Salle 5",
    type: "Classe",
    locationX: 28,
    locationY: 4,
    superficie: 100,
  },
  {
    id: 7,
    name: "Direction",
    type: "Class",
    locationX: 10,
    locationY: 14,
    superficie: 100,
  },
  {
    id: 8,
    name: "Salle Conférence",
    type: "Class",
    locationX: 17,
    locationY: 9,
    superficie: 150,
  },
  {
    id: 9,
    name: "Toillet 2",
    type: "Class",
    locationX: 2,
    locationY: 2,
    superficie: 150,
  },

  // {
  //   id: 5,
  //   name: "Room 5",
  //   type: "Class",
  //   locationX: 3,
  //   locationY: 2,
  //   superficie: 150,
  // },
  // {
  //   id: 5,
  //   name: "Room 6",
  //   type: "Class",
  //   locationX: 3,
  //   locationY: 2,
  //   superficie: 150,
  // },
  // {
  //   id: 5,
  //   name: "Room 7",
  //   type: "Class",
  //   locationX: 4,
  //   locationY: 2,
  //   superficie: 150,
  // },
  // {
  //   id: 5,
  //   name: "Room 8",
  //   type: "Class",
  //   locationX: 5,
  //   locationY: 2,
  //   superficie: 150,
  // },
  // {
  //   id: 5,
  //   name: "Room 9",
  //   type: "Class",
  //   locationX: 6,
  //   locationY: 2,
  //   superficie: 150,
  // },
  // {
  //   id: 5,
  //   name: "Room 10",
  //   type: "Class",
  //   locationX: 7,
  //   locationY: 2,
  //   superficie: 150,
  // },
];

export default rooms;
